server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zfoxapple?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: hu960220
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.zfoxapple.jxtm.mapper

